**Presentasi Persamaan Linier**

1. Perkalian LU

In [1]:
import numpy as np
u = np.array([[4, 3, -5],
 [0, -2.5, 2.5],
 [0, 0, 12]])
l = np.array([[1, 0, 0],
 [-0.5, 1, 0],
 [2, -0.8, 1]])
print("LU=",np.dot(l, u))

LU= [[ 4.  3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


2. SPL Segitiga Atas

In [2]:
import numpy as np
A = [[-2, 7, -4], [0, 6, 5], [0, 0, 3]]
b = [[14],[5],[-8]]
print(A[1][2])

5


3. Metode Gauss

In [3]:
import numpy as np
import sys
 
n = int(input('Input jumlah variabel: '))
a = np.zeros((n,n+1))
x = np.zeros(n)
print('Input koefisien dan nilai kanan pada SPL:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))
for i in range(n):
    if a[i][i] == 0.0: 
        sys.exit('Terdapat nilai 0 pada diagonal utama') #tidak boleh ada nilai 0 pada diagonal utama
         
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i] #mencari ratio
         
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k] 
            
x[n-1] = a[n-1][n]/a[n-1][n-1] #metode sulih
 
for i in range(n-2,-1,-1):
    x[i] = a[i][n]
     
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
     
    x[i] = x[i]/a[i][i]
 
print('\nSolusi SPL adalah: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

Input jumlah variabel: 3
Input koefisien dan nilai kanan pada SPL:
a[0][0]=4
a[0][1]=5
a[0][2]=6
a[0][3]=2
a[1][0]=3
a[1][1]=1
a[1][2]=5
a[1][3]=3
a[2][0]=2
a[2][1]=1
a[2][2]=6
a[2][3]=2

Solusi SPL adalah: 
X0 = 1.07	X1 = -0.53	X2 = 0.07	

4. Metode Gauss Jordan

In [6]:
import numpy as np
import sys

n = int(input('Input jumlah variabel: '))
a = np.zeros((n,n+1)) #memasukan nilai matriks
x = np.zeros(n) #membuat matriks nol
print('Input koefisien dan nilai kanan pada SPL:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))

for i in range(n): #mencari nilai diagonal utama
    if a[i][i] == 0.0:
        sys.exit('Terdapat nilai 0 pada diagonal utama')
        
    for j in range(n):
        if i != j:
            ratio = a[j][i]/a[i][i]

            for k in range(n+1):
                a[j][k] = a[j][k] - ratio * a[i][k]

for i in range(n):
    x[i] = a[i][n]/a[i][i]

print('\nSolusi SPL adalah: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

Input jumlah variabel: 3
Input koefisien dan nilai kanan pada SPL:
a[0][0]=3
a[0][1]=-0.1
a[0][2]=-0.2
a[0][3]=7.85
a[1][0]=0.1
a[1][1]=7
a[1][2]=-0.3
a[1][3]=-19.3
a[2][0]=0.3
a[2][1]=-0.2
a[2][2]=10
a[2][3]=71.4

Solusi SPL adalah: 
X0 = 3.00	X1 = -2.50	X2 = 7.00	

5. Dekomposisi LU

In [7]:
import numpy as np
import scipy.linalg
A = np.array([[4, 3, -1],
             [-2, -4, 5],
             [1, 2, 6]])
P, L, U = scipy.linalg.lu(A)
print(L)
print(U)

[[ 1.    0.    0.  ]
 [-0.5   1.    0.  ]
 [ 0.25 -0.5   1.  ]]
[[ 4.   3.  -1. ]
 [ 0.  -2.5  4.5]
 [ 0.   0.   8.5]]
